export const colorWordClass: {[key: string]: string} = {
    noun: 'text-green-300',
    particle: 'text-pink-300',
    verb: 'text-orange-300',
    adjective: 'text-yellow-300',
    conjunction: 'text-purple-300',
    interjection: 'text-red-300',
    counter: 'text-amber-200',
    pronoun: 'text-lime-200',
    adverb: 'text-emerald-300',
    //Capital
    Noun: 'text-green-300',
    Particle: 'text-pink-300',
    Verb: 'text-orange-300',
    Adjective: 'text-yellow-300',
    Conjunction: 'text-purple-300',
    Interjection: 'text-red-300',
    Counter: 'text-amber-200',
    Pronoun: 'text-lime-200',
    Adverb: 'text-emerald-300',
  };